name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm i pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Build the project
        run: pnpm build
